---
- name: Get system architecture
  ansible.builtin.command: dpkg --print-architecture
  register: __system_arch
  changed_when: false
  check_mode: false

- name: Is it installed?
  ansible.builtin.stat:
    path: /usr/bin/tempo
  register: __tempo_stat

- name: Get version
  ansible.builtin.command: /usr/bin/tempo -version
  changed_when: false
  register: __tempo_version_out
  when: __tempo_stat.stat.exists

- name: Set version
  ansible.builtin.set_fact:
    __tempo_version: "{{ __tempo_version_out.stdout_lines[0].split(' ')[2] | replace('v', '') }}"
  when: __tempo_stat.stat.exists

- name: Empty tempo version if not installed
  ansible.builtin.set_fact:
    __tempo_version: ""
  when:
    - __tempo_version is not defined

- block:
    - name: Download Tempo Debian package
      ansible.builtin.get_url:
        url: "https://github.com/grafana/tempo/releases/download/v{{ tempo_version }}/tempo_{{ tempo_version }}_linux_{{ __system_arch.stdout }}.deb"
        dest: "/tmp/tempo_{{ tempo_version }}.deb"
        checksum: "sha256:https://github.com/grafana/tempo/releases/download/v{{ tempo_version }}/SHA256SUMS"
        mode: '0644'
      register: _download_release
      until: _download_release is succeeded
      retries: 5
      delay: 2

    - name: Install Tempo Debian package
      ansible.builtin.apt:
        deb: "/tmp/tempo_{{ tempo_version }}.deb"

    - name: Clean-up
      ansible.builtin.file:
        path: "/tmp/tempo_{{ tempo_version }}.deb"
        state: absent
  check_mode: false
  when:
    - __tempo_version != tempo_version
